forum_home:
    pattern:  /
    defaults: { _controller: EpixaForumBundle:Category:index }

forum_category_annotations:
    resource: "@EpixaForumBundle/Controller/CategoryController.php"
    type:     annotation
    prefix:   /category

forum_topic_annotations:
    resource: "@EpixaForumBundle/Controller/TopicController.php"
    type:     annotation
    prefix:   /topic

forum_post_annotations:
    resource: "@EpixaForumBundle/Controller/PostController.php"
    type:     annotation
    prefix:   /post